# CH OS central colors

CH_BG="#030606"
CH_PANEL="#071010"
CH_PANEL_2="#06110f"
CH_SELECTED="#0f2f29"
CH_BORDER_DARK="#137a66"
CH_BORDER="#1edbb2"
CH_FG="#2fffd0"
CH_MUTED="#0d4f43"

CH_FONT="JetBrainsMono Nerd Font 13"
CH_MONO_FONT="JetBrainsMono Nerd Font"
